name: Flutter Windows Release Build

on:
  # تشغيل عند الدفع إلى الفرع الرئيسي
  push:
    branches: [ "main", "master" ]
  # يمكن التشغيل يدوياً من واجهة GitHub
  workflow_dispatch: 

# تعريف متغير ثابت لإصدار Flutter
env:
  FLUTTER_VERSION: '3.35.7' # استخدم الإصدار الخاص بك لضمان التوافق

jobs:
  build_windows:
    runs-on: windows-latest # تحديد بيئة التشغيل لـ Windows

    steps:
    - name: 1. Checkout Code
      uses: actions/checkout@v4

    - name: 2. Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        # هذا يضمن وجود أدوات Visual Studio C++ المطلوبة للبناء على Windows Runner
        
    - name: 3. Enable Windows Desktop Support
      # خطوة مهمة جداً: تخبر Flutter بإنشاء ملفات البناء الخاصة بالويندوز
      run: flutter config --enable-windows-desktop

    - name: 4. Get Dependencies
      run: flutter pub get
    
    - name: 5. Build Windows Executable (Release)
      # إنشاء البناء النهائي (Release)
      run: flutter build windows --release

    - name: 6. Upload Windows Artifact
      # حفظ مجلد البناء الناتج كملف قابل للتحميل
      uses: actions/upload-artifact@v4
      with:
        name: Windows-App-Release
        # المسار الافتراضي لملفات الإطلاق في Flutter Windows
        path: build/windows/runner/Release/
        retention-days: 7 # الاحتفاظ بالملف لمدة 7 أيام
